use anyhow::{Context, Result};
use std::fs;
use std::path::{Path, PathBuf};

use super::resolver::ResolvedProject;

pub const GENERATED_CMAKE_PATH: &str = "cmake/wtr_modules.cmake";

fn render_list(name: &str, values: &[String]) -> String {
    if values.is_empty() {
        return format!("set({name})\n");
    }

    let items = values
        .iter()
        .map(|value| format!("    {value}"))
        .collect::<Vec<_>>()
        .join("\n");
    format!("set({name}\n{items}\n)\n")
}

pub fn generate_string(resolved: &ResolvedProject) -> String {
    let repositories = resolved
        .repositories
        .iter()
        .map(|repository| repository.name.clone())
        .collect::<Vec<_>>();
    let mut resolved_targets = resolved
        .managed_packages
        .iter()
        .map(|package| package.pkgname.clone())
        .collect::<Vec<_>>();
    for target in &resolved.external_targets {
        if !resolved_targets.contains(target) {
            resolved_targets.push(target.clone());
        }
    }

    let mut content = String::new();
    content.push_str("include_guard(GLOBAL)\n\n");
    content.push_str("# Generated by cpkg sync.\n");
    content.push_str(
        "# Include this file from the root CMakeLists.txt of your STM32CubeMX project.\n\n",
    );
    content.push_str(&render_list("WTR_MANAGED_REPOSITORIES", &repositories));
    content.push('\n');
    content.push_str(
        r#"foreach(_wtr_repo IN LISTS WTR_MANAGED_REPOSITORIES)
    if(NOT EXISTS "${CMAKE_CURRENT_LIST_DIR}/../Modules/${_wtr_repo}/CMakeLists.txt")
        message(FATAL_ERROR "Missing managed repository '${CMAKE_CURRENT_LIST_DIR}/../Modules/${_wtr_repo}'. Run cpkg sync.")
    endif()

    add_subdirectory(
        "${CMAKE_CURRENT_LIST_DIR}/../Modules/${_wtr_repo}"
        "${CMAKE_BINARY_DIR}/cpkg/${_wtr_repo}"
    )
endforeach()

"#,
    );
    content.push_str(&render_list(
        "WTR_DIRECT_PACKAGE_TARGETS",
        &resolved.direct_targets,
    ));
    content.push('\n');
    content.push_str(&render_list(
        "WTR_RESOLVED_PACKAGE_TARGETS",
        &resolved_targets,
    ));
    content.push('\n');
    content.push_str("add_library(wtr_project_dependencies INTERFACE)\n");
    if !resolved.direct_targets.is_empty() {
        content.push_str(
            "target_link_libraries(wtr_project_dependencies INTERFACE ${WTR_DIRECT_PACKAGE_TARGETS})\n",
        );
    }
    content.push('\n');
    content.push_str("function(wtr_link_packages target)\n");
    if !resolved.direct_targets.is_empty() {
        content.push_str(
            "    target_link_libraries(${target} PUBLIC ${WTR_DIRECT_PACKAGE_TARGETS})\n",
        );
    }
    content.push_str("endfunction()\n");
    content
}

pub fn write_integration_file(root: &Path, resolved: &ResolvedProject) -> Result<PathBuf> {
    let path = root.join(GENERATED_CMAKE_PATH);
    let parent = path
        .parent()
        .ok_or_else(|| anyhow::anyhow!("invalid generated CMake path"))?;
    fs::create_dir_all(parent).context("failed to create generated CMake directory")?;
    fs::write(&path, generate_string(resolved)).context("failed to write generated CMake file")?;
    Ok(path)
}

#[cfg(test)]
mod tests {
    use super::generate_string;
    use crate::project::resolver::{ManagedRepository, ResolvedPackage, ResolvedProject};

    #[test]
    fn generate_string_emits_repositories_and_targets() {
        let content = generate_string(&ResolvedProject {
            direct_targets: vec!["MotorDrivers::DJI".to_string()],
            external_targets: vec!["stm32cubemx".to_string()],
            managed_packages: vec![
                ResolvedPackage {
                    pkgname: "bsp::CANDriver".to_string(),
                    repo: "BasicComponents".to_string(),
                    path: "Modules/BasicComponents/bsp/can_driver".to_string(),
                    dependencies: vec!["stm32cubemx".to_string()],
                },
                ResolvedPackage {
                    pkgname: "MotorDrivers::DJI".to_string(),
                    repo: "MotorDrivers".to_string(),
                    path: "Modules/MotorDrivers/motors/DJI".to_string(),
                    dependencies: vec!["bsp::CANDriver".to_string()],
                },
            ],
            repositories: vec![
                ManagedRepository {
                    name: "BasicComponents".to_string(),
                    url: "https://github.com/HITSZ-WTRobot-Packages/BasicComponents.git"
                        .to_string(),
                    rel_path: "Modules/BasicComponents".to_string(),
                },
                ManagedRepository {
                    name: "MotorDrivers".to_string(),
                    url: "https://github.com/HITSZ-WTRobot-Packages/MotorDrivers.git".to_string(),
                    rel_path: "Modules/MotorDrivers".to_string(),
                },
            ],
        });

        assert!(content.contains("WTR_MANAGED_REPOSITORIES"));
        assert!(content.contains("BasicComponents"));
        assert!(content.contains("MotorDrivers::DJI"));
        assert!(content.contains("add_library(wtr_project_dependencies INTERFACE)"));
    }
}
